Hooks:Add("LocalizationManagerPostInit", "packaging_services", function(loc) 
	LocalizationManager:add_localized_strings({
		--Menu Stuff
		menu_st_active_spec = "Equipment: $specialization",	
		menu_specialization = "Packaging Services",

		--Perk Deck Names and Descriptions
		menu_st_spec_1 = "Chief of Staff:",
		menu_st_spec_1_desc = "Kapodzimim, a former housewife, is also known as a criminal offender. The expert has a high position in the army and points directly to the commander or his deputy.\n\nIf the author wants to talk to someone, the leader of the organization, their army will take care of it.",
		menu_st_spec_2 = "Power",	
		menu_st_spec_2_desc = "Power is a tough guy who will use violence to send a message to a team leader. They are the backbone of criminal organizations.\n\nMuscles work when you need to bend anyone, break a leg, break a head, or warn an owner.",
		menu_st_spec_3 = "Another Weapon",	
		menu_st_spec_3_desc = "The main developer is a military expert. The contractor is responsible for the maintenance, repair and repair of the equipment.\n\nEvery family needs something that the security forces can provide to accomplish their task.",
		menu_st_spec_4 = "The Gospels",	
		menu_st_spec_4_desc = "Bullies are dangerous criminals who can use deception and deadly violence. Versatile thugs and thieves are hired to do everything from package pickup to theft.\n\nTrash has potential. What is missing is technology.",
		menu_st_spec_5 = "Sign in",
		menu_st_spec_5_desc = "Hitman is an experienced hitman with a good character in the criminal world.\n\nCriminal bodies are an important source of criminal power, revenge or loss of power.",	
		menu_st_spec_6 = "Thefts",	
		menu_st_spec_6_desc = "Many of them have shortcomings. That idea sounds like a crime.\n\nBut copying affects everything. And he's not the only winner who steals, lies, cheats and offends or misses.",
		menu_st_spec_7 = "The House is Destroyed",	
		menu_st_spec_7_desc = "The power of thieves is more valuable than a simple attack. Its creators allow thieves to open up, cover their bodies, and quickly observe the noise. They also fight to win wars. They sat down and left.\n\nThis body workout gives the pain reliever user the ability to heal wounds quickly.",
		menu_st_spec_8 = "He Took It",	
		menu_st_spec_8_desc = "Insiders are agents who hire government and criminal organizations and are excellent at gathering information about their enemies as well as companies to obtain trade secrets from their competitors.\n\nThe intruder is a rebel movement expert who knows how to deal with the environment.",
		menu_st_spec_9 = "Social Patience",	
		menu_st_spec_9_desc = "We all know that a candidate is one of the most offenders. Big companies will avoid this if it works, but it is difficult to fix.\n\nWorking hard, they are brave, rude, talk nice and mean. Although enemies in the community are not criminals, they are the most dangerous enemies.",
		menu_st_spec_10 = "Toys",	
		menu_st_spec_10_desc = "Little opportunity to reach the end of the line, intelligence, power. Some do.\n\nThe level of success is incredible. The ancient Greeks saw this as a divine plan. Error Yes, but you can save. All preparation is necessary for payment and the result will be greater than your income. The card number is random.\n\nSuper Deck is a great card. The winner will help one team win, but the player will win one.",
		menu_st_spec_11 = "Mechanic",
		menu_st_spec_11_desc = "A typical treadmill is a worker who can master and turn around difficult situations.\n\nThe damage the factory inflicts on the enemy depends on their height and high penalty.",	
		menu_st_spec_12 = "I.",
		menu_st_spec_12_desc = "Gangster are one of the most criminal organizations in the world. The Oban-run Niquino-controlled jacuzzi was known for its aggressive nature, improved nature, and systemic support.\n\nThose exiled and abandoned by the yakuza community know how to escape. He looks calm, but he's not in despair.",	
		menu_st_spec_13 = "Former President",
		menu_st_spec_13_desc = "The Former President is the bravest refugee in the world. Extinct lovers. Fear of death forces them to move closer to success.\n\nThe Former President did not follow the rules, but followed the great Jockey 8 and tried to respect nature.",	
		menu_st_spec_14 = "Throw",	
		menu_st_spec_14_desc = "Paul Manik Park is a good support in bad weather. For a friend who does hard work and constant humor, there will be a few temporary places I forgot to run into.",
		menu_st_spec_15 = "Worry",	
		menu_st_spec_15_desc = "They want chaos to enforce the laws of nature. Kings, queens and presidents do not make it easy for me to tolerate bad influences. Go your own way. Criminals can harm others by leaving new security. Using",
		menu_st_spec_16 = "Rad",	
		menu_st_spec_16_desc = "Cycling teams are feared all over the world and the largest organizations are common names. Be strict and fair when driving and understand that the rules of the club are the same. Cyclists are cruel and rebellious and are not afraid to turn on those who do not want to cross.\n\nWhen you cycle up the stairs, everything says ##1## percent. ##1%## of respondents refused to comply with EU law and are labeled as 'illegal'. When it comes to cycling, it all depends on the travels and journeys of the members.",
		menu_st_spec_17 = "The Other is a Spot Plow",	
		menu_st_spec_17_desc = "Spot Plow is the leader, and the driver must follow every strategy. But first you need to be rich. When you make money, you have power. Remember, simple balls rule the world.",
		menu_st_spec_18 = "Murderer",	
		menu_st_spec_18_desc = "##Consent of drug dealers is required##. Intoxicants solve a variety of problems. Discussing is not natural. They can work quickly and without fear",
		menu_st_spec_19 = "Stand",	
		menu_st_spec_19_desc = "You are on a calm path that cannot be broken. Warning spirits can help resolve mountain situations that can intimidate and saddle others. The monk teaches how to regulate breathing and physical response and tells the enemy to get up and work.",
		menu_st_spec_20 = "Group logo:",
		menu_st_spec_20_desc = "Some say the experience is better than sharing, even with better aerosol performance! For specific instructions that are right for you, this may include bank robbery and operational activities.",	
		menu_st_spec_21 = "Me",
		menu_st_spec_21_desc = "You can kneel down in front of the security system that initiated the command by clicking the button. Cameras and guards won't be able to see, but if things don't go their way, they can attack enemy data to scare your viewers.",

		--Even Cards
		menu_deckall_2 = "Power Pop",	
		menu_deckall_2_desc = "Increase the performance of your headphones by ##25%##.",
		menu_deckall_4 = "Together:",	
		menu_deckall_4_desc = "##+1## for more details.\n\nWhen using this tool, the speed increases by ##15%##.\n\nAfter a working day you will get more than ##45%## experience.",
		menu_deckall_6 = "Large Room",	
		menu_deckall_6_desc = "Open the toolbox in use. Can be used to purchase weapons.\n\nThe size of his weapon has increased to ##135%## of the order.",
		menu_deckall_8 = "Wild Speed",	
		menu_deckall_8_desc = "You get ##5%##. It is not used for armored vehicles, grenade launchers or vehicles.\n\nThe flow of medical bags increased by ##20%##.",


		--Actual Decks
		menu_deck1_1 = "Huge Force",
		menu_deck1_1_desc = "Reduce the loss of friends by ##8%##. If you are under ##50##, this ratio will double.",
		menu_deck1_3 = "Men's Marathon",
		menu_deck1_3_desc = "You and your body are ##50%## confident.\n\nThe cutting speed is improved by up to ##25%##.\n\nWhen you are in the middle of an enemy element, you destroy ##6%## more than the enemy.\nNote: Employee benefits are not allowed.",
		menu_deck1_5 = "Wolf Wolf.",
		menu_deck1_5_desc = "You still have ##10## health members on your team.\n\nYou have ##20%## health.\n\nOverview: No group interests are expected.",
		menu_deck1_7 = "Wheel by Wheel",
		menu_deck1_7_desc = "Get ##10%## more weapons and ##5%## more workers.\n\n##Remember: the workers disappeared.##",
		menu_deck1_9 = "Other Features",
		menu_deck1_9_desc = "You and your team get ##6%## health and ##12%## off each enemy.\n\nIf you have one or more accidents, you and your team can reduce the damage by ##8%##.\n\nsymptoms. Your benefits will not be reduced.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck2_1 = "Huge Force",
		menu_deck2_1_desc = "It provides more than ##10%## health.",
		menu_deck2_3 = "Meat Restrictions",
		menu_deck2_3_desc = "When you are around your ##partner##, your goal is ##15%##.\n\nYour health is better than ##10%##.",
		menu_deck2_5 = "Julie",
		menu_deck2_5_desc = "Get ##20%## strength.",
		menu_deck2_7 = "To Disturb the Tranquility",
		menu_deck2_7_desc = "Any weapon can cause ##fear## in enemies.\n\nThe fear of the enemy immediately turns into ##irregular terror.##",
		menu_deck2_9 = "The Torquatus Weighs 800 Pounds.",
		menu_deck2_9_desc = "More than ##40%## healthy.\n\nChange ##3## percent of your life every ##5## seconds.",

		menu_deck3_1 = "Anchor Point Type 1:",
		menu_deck3_1_desc = "Get more than ##10%## equipment",
		menu_deck3_3 = "Type II link",
		menu_deck3_3_desc = "You get ##10%## of the army.",
		menu_deck3_5 = "Types of Divorce 3",
		menu_deck3_5_desc = "Receive ##10%## training.",
		menu_deck3_7 = "Improved Tank",
		menu_deck3_7_desc = "Increase the processing speed of banks by ##10%.##\nIt doesn't matter if the shield is empty for a few seconds. Do this more than once for more than ##15## seconds.",
		menu_deck3_9 = "Rain War",
		menu_deck3_9_desc = "Obtain more than ##5%## of your weapon.\n\nUsing email reduces download time by ##10%## for you and your staff.\n\nNote: Employees do not receive benefits.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck4_1 = "I Do Not Understand",
		menu_deck4_1_desc = "Increase the boiling probability to ##15%##.",
		menu_deck4_3 = "Impossible",
		menu_deck4_3_desc = "Closing the audience by ##15%## increases your chances of achieving the goal.",
		menu_deck4_5 = "Stop",
		menu_deck4_5_desc = "Light energy increased by ##15%##.",
		menu_deck4_7 = "But Really Cool",
		menu_deck4_7_desc = "You will increase your chances of harvesting by ##15%##.",
		menu_deck4_9 = "Sensitivity to Murder",
		menu_deck4_9_desc = "##25%## chance of throwing all weapons into enemy weapons.\n\nWeapons increase by ##80%##.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck5_1 = "Early Recovery",
		menu_deck5_1_desc = "The gun return rate increased by ##5%##.",
		menu_deck5_3 = "Eternal",
		menu_deck5_3_desc = "Fines for two fights increased to ##-16##.\n\nIncrease the speed by ##10%##.\n\nAkimbo increases weapon power by ##50%##.",
		menu_deck5_5 = "Nutrition",
		menu_deck5_5_desc = "Defense rate of return increased by ##10%##.",
		menu_deck5_7 = "Artistic Revival",
		menu_deck5_7_desc = "Increase your weapon by ##10%##.",
		menu_deck5_9 = "Teeth and Nails",
		menu_deck5_9_desc = "Weapons rehabilitation has increased by ##10%##.\n\nAfter damage, the shield returns for ##1.5## seconds. anyway\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck6_1 = "I Do Not Understand",
		menu_deck6_1_desc = "Increase the boiling probability to ##15%##.",
		menu_deck6_3 = "Basic Leave",
		menu_deck6_3_desc = "Wearing dangerous clothing extends life expectancy by ##5%##.\n\nWeapons increased by ##20%##.",
		menu_deck6_5 = "Very Advanced",
		menu_deck6_5_desc = "The probability of avoiding a booking increases by ##10%##.\n\nWeapons increased by ##20%##.",
		menu_deck6_7 = "Professional Beauty",
		menu_deck6_7_desc = "The likelihood increases by ##10%## in tumors.\n\nYour hands on the bed will increase by ##25%##.",
		menu_deck6_9 = "Master of the Resurrection",
		menu_deck6_9_desc = "The number of veterans has increased by ##10%##.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck7_1 = "Without Feeling",
		menu_deck7_1_desc = "The gain of the shield was increased by ##20%##.",
		menu_deck7_3 = "Try the Trick",
		menu_deck7_3_desc = "You don’t really want to have ##10%## on your knees.\n\nYou are ##20%## faster than dying.",
		menu_deck7_5 = "Good Luck In Ireland",
		menu_deck7_5_desc = "The chance of escape increases by ##5%##.\n\nThe chance of reaching the goal is reduced by an additional ##5%## if you get up and bend down.\n\nThe open rate increased by ##20%##.",
		menu_deck7_7 = "Dutch Hero",
		menu_deck7_7_desc = "Your chance of escape increases by another ##5%##.\n\nYour chances of reaching the goal from a standing or squatting position are reduced by another ##5%##.\n\nRespond to customers ##10%## faster.",
		menu_deck7_9 = "Fresh Air",
		menu_deck7_9_desc = "It stays in place and returns the defense speed to ##20%##.\n\nHis fastest speed is just over ##10##.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck8_7 = "Horse and Dog",
		menu_deck8_7_desc = "When three or more enemies surround you, the enemy damage is ##12%##.\n\nAny music between the ##second## and ##second## songs leads to normal loss.",
		menu_deck8_1 = "Problem Solving",
		menu_deck8_1_desc = "If you stay away from the enemy, you will get ##8%## less damage than the enemy.",
		menu_deck8_3 = "Hand to Hand Fighting",
		menu_deck8_3_desc = "If you are in the middle of an enemy house, you take ##8%## extra damage from the enemy.",
		menu_deck8_5 = "Good in Unarmed Combat",
		menu_deck8_9 = "Be Clean",
		menu_deck8_9_desc = "Attacking an enemy with a weapon will give you ##20%## of your life. This should not happen more than once every ##10## seconds.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck9_1 = "Horse and Dog",
		menu_deck9_1_desc = "When three or more enemies surround you, the enemy damage is ##12%##.\n\nAny music between the ##second## and ##second## songs leads to normal loss.",
		menu_deck9_3 = "Happiness",
		menu_deck9_3_desc = "After destroying the enemy, ##30## shields will be returned.\n\nThis should not be done more than ##once## per second.\n\nGet ##10%## more weapons.",
		menu_deck9_5 = "Clean Food",
		menu_deck9_5_desc = "Destroy enemies with precision weapons and gain ##10%## health.\n\nThis should not occur more than ##once## per second.\n\nIf you can be attacked by an enemy, you lose less than ##8%##.",
		menu_deck9_7 = "Cooker",
		menu_deck9_7_desc = "The slaughter of the enemy returns in the ##middle## of the arms.\n\nThis should not last longer than the second ##one##.\n\nYou also get ##10%## more equipment.",
		menu_deck9_9 = "Conflict",
		menu_deck9_9_desc = "If you kill an enemy at a distance, ##75%## of the fear arises between them.\n\nThe fear of the enemy will cause short-term fears that he will not stand.\n\nThis should not be done more than ##once## a second.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck10_1 = "Meet the team",
		menu_deck10_1_desc = "The ammunition you collect also includes medical supplies and improves health from ##16## to ##24##.\n\nThis should not happen more than once every ##3## seconds.\n\nIf the total strength of the player is less than the ##other##, the therapeutic effect of the player is increased by ##20%##. three times.",
		menu_deck10_3 = "Ammunition Was Provided",
		menu_deck10_3_desc = "When you collect ammo, your entire team will start collecting ammo for ##50%## by collecting other players.\n\nIt cannot be done more than once every ##5## seconds.\n\nYou get ##20%## more health.",
		menu_deck10_5 = "Office Work",
		menu_deck10_5_desc = "With a deposit, you can get ##50## of your employees.\n\nIncreases health by ##20%##.",
		menu_deck10_7 = "Wow, Treat Me",
		menu_deck10_7_desc = "Raise the health level of the pill to ##8##.",
		menu_deck10_9 = "Prevention and Health Protection",
		menu_deck10_9_desc = "The health case has been increased by ##8## units.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck11_1 = "Z ai",
		menu_deck11_1_desc = "The enemy kills and heals ##1## hp every ##0.3## seconds for ##3## seconds.\n\nThese problems can be improved, but if you have a bulletproof vest or jumper you can only see it once every ##1.5## seconds.",
		menu_deck11_3 = "S is Online",
		menu_deck11_3_desc = "It heals the damage you are doing now and improves ##2## health points in ##0.3## seconds - ##3## seconds.\n\nYour health is ##20%## better",
		menu_deck11_5 = "Good Luck!",
		menu_deck11_5_desc = "Announce the enemy. Come back in ##three## seconds\n\nIncreases the chance to destroy enemy weapons by ##10%##.",
		menu_deck11_7 = "Dwby̰you",
		menu_deck11_7_desc = "When he hits an enemy, he recovers ##4##, ##3##, and ##0.3## every second.\n\nHealth increased by ##20%##.",
		menu_deck11_9 = "Xngan",
		menu_deck11_9_desc = "In ##0.3## seconds, the health of all enemies is ##4.2##.\n\nThe supply of weapons is growing by ##20%##.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck12_1 = "Carpet Sign",
		menu_deck12_1_desc = "Replenish your health-damaging stones. If your health is below ##25%##, you can upgrade your weapon to ##20%##.\n\nBut if you are in this healing operation, all ##three## sides will be removed.",
		menu_deck12_3 = "Bat",
		menu_deck12_3_desc = "The harder you get, the faster you go. If you have ##25%## health left, you can get up to ##20%## faster.",
		menu_deck12_5 = "Thanks Fresh",
		menu_deck12_5_desc = "The lower your life, the faster the job will be offered. When you have ##25%## daily life you get ##20%## to upgrade your weapon.",
		menu_deck12_7 = "The Death of a Dragon.",
		menu_deck12_7_desc = "The lower the health, the stronger the power. With a health reduction of ##25%##, the temporary increase in the number of acids increases to ##20%##.",
		menu_deck12_9 = "Anime Tattoo",
		menu_deck12_9_desc = "Each class has ##25%## health, not ##50%##.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck13_1 = "Confirm The Point",
		menu_deck13_1_desc = "Moving the shields saves ##4## life for each enemy or team killed.\n\nWhen you run out of arms and begin to recover, you will be just like you are now.\n\nThe cheapest sound depends on your device.",
		menu_deck13_3 = "Electricity Required",
		menu_deck13_3_desc = "Get well soon.\n\nGet ##10%## health.",
		menu_deck13_5 = "Survive in the Snow",
		menu_deck13_5_desc = "Get ##50%## of maximum energy\n\n##10%## increase\n\n##10%## reduction in risk of loss",
		menu_deck13_7 = "World of Wisdom",
		menu_deck13_7_desc = "Improve your health by getting rid of ##4K##.\n\n##20%## better health.",
		menu_deck13_9 = "Direct Routes",
		menu_deck13_9_desc = "Defeating the enemy shortens the length of the weapon.\nAftercare after release.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck14_1 = "Faith",
		menu_deck14_1_desc = "##100%## damage changes on about ##240## tracks every ##4## seconds, the maximum number of columns is ##600##.\n\n##Anarchy:##\nWater ##1## candle for every ##30## perennials. The volume of the object decreases from ##60 ٪## + ##80## per ##8## seconds.",
		menu_deck14_3 = "The Spread of the Disease",
		menu_deck14_3_desc = "Participants on the boat will reap the rewards of your exciting journey.\n\nMost users cannot control the amount of data, because data loss will have a greater impact.",
		menu_deck14_5 = "Sun",
		menu_deck14_5_desc = "So change your hysteria distribution to ##60%## + ##40## in ##8## seconds.",
		menu_deck14_7 = "You Work Carelessly",
		menu_deck14_7_desc = "For each of the ##25## isopenic funds, change the damage from the isopenic pool to damage with you and your team ##1##.",
		menu_deck14_9 = "Bullia",
		menu_deck14_9_desc = "Stax's Insanity Absorption Absorption can boost you ##100%##.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck15_1 = "Flash of Lightning",
		menu_deck15_1_desc = "Instead of fully upgrading weapons during war, weapons are continually upgraded during war. Heavy armor improves many weapons, but is durable.\n\nIf you run out of weapons, you will not lose ##2## seconds of life, which does not happen every ##15## seconds.\n\nNote: This feature removes skills and tools to speed up weapon maintenance.",
		menu_deck15_3 = "With",
		menu_deck15_3_desc = "##50%## of your health is a ##100%## weapon.",
		menu_deck15_5 = "Death or Glory?",
		menu_deck15_5_desc = "##50## live ##110## weapons.",
		menu_deck15_7 = "To Increase",
		menu_deck15_7_desc = "##120%## to ##50%## of your health becomes a weapon.",
		menu_deck15_9 = "Life is Hard",
		menu_deck15_9_desc = "It takes ##10## shields to heal an injury - just ##one## action in ##1.5## seconds.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck16_1 = "View",
		menu_deck16_1_desc = "If the team is right, you get ##five## lives, which is ##three## to ##three## seconds",
		menu_deck16_3 = "Lion Cub",
		menu_deck16_3_desc = "Every ##10%## of random calls, the number of weapons will ##increase##.",
		menu_deck16_5 = "Way",
		menu_deck16_5_desc = "About ##10%## of a lost person's health is reduced by cooling for up to ##4## seconds in a ##0.1## second shower.",
		menu_deck16_7 = "Policeman",
		menu_deck16_7_desc = "For every ##10%## of the transferred weapons, the killer's health increases by ##1## kill.",
		menu_deck16_9 = "Print",
		menu_deck16_9_desc = "Loss of protection by ##10%## reduces the rest level from ##0.1## to ##0.1## seconds.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck17_1 = "Bad Boy",
		menu_deck17_1_desc = "See also Spot Plow before riding. A huge fan of the State of Desire Fall pfan-remove this statement.\n\nPress the Play Button, hold your nose and cover your uterus for ##5-5## seconds.\n\ncause general problems Group service can be completed in ##30## seconds.",
		menu_deck17_3 = "Rough Game",
		menu_deck17_3_desc = "You will get a health score of up to ##10%##.",
		menu_deck17_5 = "This Is The Enemy Of The People",
		menu_deck17_5_desc = "Increases health by ##10%##.\n\nWhen it comes to ##romance##, men want to show how ##strong## you are.",
		menu_deck17_7 = "With Ballet",
		menu_deck17_7_desc = "Physical strength increased by ##20%##\n\nThe health benefits of injection increased by ##25%##, but less than ##50%##.",
		menu_deck17_9 = "Until",
		menu_deck17_9_desc = "There are more than ##40## health centers.\n\nFor ##5## results of measles vaccine, health is reduced by ##1## second.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",
		bm_ability_chico_injector = "Play Button",
		bm_ability_chico_injector_desc = "Free with a permanent bonus guarantee included\n\nWhen used, the user will no longer experience pain and fear. Pain can make a person angry in the middle of a fight; Lack of fear is a clear and horrifying threat to the enemy.",

		menu_deck18_1 = "Kea",
		menu_deck18_1_desc = "Hide grenades, fire and flames!\n\nDive into the smoke with a Fire Engine for ##10## seconds. Your unit completely removes ##50%## of the shells. Enemy smoke detection is reduced by ##50%##.\n\nAfter the ##X-rays## disappear, the Fire Engines cool a bit. But this is the best time to kill the enemy",
		menu_deck18_3 = "Twitter",
		menu_deck18_3_desc = "When a player is killed, there is a ##20%## chance of escape. The effect will return immediately after the player has passed, and will not be visible for the next ##four## seconds.",
		menu_deck18_5 = "I Do Not Understand",
		menu_deck18_5_desc = "Increase the boiling probability to ##15%##.",
		menu_deck18_7 = "The Push is Complete",
		menu_deck18_7_desc = "Dodging fills the hand.",
		menu_deck18_9 = "Loss of Vision",
		menu_deck18_9_desc = "The window guarantees ##100%## of all shot results. Even if your friend smokes in the window, he has a ##10%## chance.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",
		bm_grenade_smoke_screen_grenade = "Fire Engines",
		bm_grenade_smoke_screen_grenade_desc = "He needed more suicide.\n\nIf you leave one of them, enter the clouds and fight the enemies to test yourself. Bake when the balls do not appear directly.",

		menu_deck19_1 = "Good Idea",
		menu_deck19_1_desc = "Selling Lagerbanken and its accessories\n\nDamage is now reduced by ##75%##, remaining damage is immediately charged.\n\notherwise, Losses decrease by ##75%## over time (##12## seconds).\n\nYou can open a replacement jar by pressing the back button and immediately ignore the damage. Pumpkin is cooled for ##10## seconds, but the time remaining for each enemy killed is reduced by ##1## second.",
		menu_deck19_3 = "It Doesn’t Run Smoothly",
		menu_deck19_3_desc = "Damage to your body or your body can harm your health.",
		menu_deck19_5 = "Relax",
		menu_deck19_5_desc = "If you are not injured for ##4## seconds, the damage will be removed from your waiting list.",
		menu_deck19_7 = "Impossible",
		menu_deck19_7_desc = "If health is less than ##35##, the balloon's cooling time for that enemy is reduced to ##2## seconds.",
		menu_deck19_9 = "Entinye Hoomanawanui",
		menu_deck19_9_desc = "The ##maximum%## increase will deal with the problem.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",
		bm_grenade_damage_control = "Lagerbanken",
		bm_grenade_damage_control_desc = "Must maintain a high level of PERKO\n\nThis year in 1882, when an old ship was working with a Buddhist monk, the governor wrote the words Stoke and JW spirit. The Duke gave him his favorite whiskey. Swallowing fish is a warning signal that Zen will stand for a while to minimize damage to the user.",

		menu_deck20_1 = "Landscape Atlas",
		menu_deck20_1_desc = "Open and use The Machine.\n\nTo drive a car, you need to see the right button ##18 m## and press the save button to make the light come on.\n\nEach of your enemies or the unit you are selecting will keep you healthy at ##7.5## ##15## u per unit.\n\nThe duration of each enemy you kill is increased by ##1.3## seconds and decreased by ##two## seconds.\n\nThe end time is ##2## seconds and the freezing time is ##12## seconds.",
		menu_deck20_3 = "Ganga",
		menu_deck20_3_desc = "Maximum power of ##20## increases",
		menu_deck20_5 = "Unity",
		menu_deck20_5_desc = "Your enemy or surname gives you ##2## to ##2## victories.\n\nThis effect is maintained for the duration of the wait until the relief is lost.",
		menu_deck20_7 = "Lift a Little",
		menu_deck20_7_desc = "Your overall health has improved by ##20## percent.",
		menu_deck20_9 = "Consistent",
		menu_deck20_9_desc = "This time reduces the time required to remove the item from the board by ##2## seconds until the opponent who killed a party reaches the timer.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",
		bm_grenade_tag_team = "The Machine",
		bm_grenade_tag_team_desc = "Chemical Test Cost: A Test for All Variables\n\nThe Machine improves the body's heart rate and has a therapeutic effect on the user.",

		menu_deck21_1 = "Statistical Analysis",
		menu_deck21_1_desc = "Open Pocket ECM and install the application.\nWhen I open a new test session, the Pocket ECM monitor does not work. Do not carry the ECM in a bag. If necessary, you can loosen it.\nYou can use the navigation buttons to open the ECM pocket during the display.\nTurn on the ECM on the bag before the sound to improve shake perception and generate vibration and vibration in ##6## seconds.\nUse ECM in the bag when cannon strength increases responsibility, allowing you to use ##6## cards in each round to dodge enemies. Number ##2##\nThe original ECM application is worth your money with a time limit of ##100## hours, but what you do is damaged in ##6## seconds.",
		menu_deck21_3 = "Fair Enough",
		menu_deck21_3_desc = "##20%## will be healthy.",
		menu_deck21_5 = "Well Rotten",
		menu_deck21_5_desc = "Reaction to kill the enemy with a healthy recovery ##20##.",
		menu_deck21_7 = "Other Optional Answers",
		menu_deck21_7_desc = "Destroy at least ##one## enemy while working on targets or block ##20## shots in ##30## seconds.",
		menu_deck21_9 = "Kukuikipuka",
		menu_deck21_9_desc = "Members of the pilots who killed the enemy in the counterattack worked to restore the health of ##10## people.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",
		bm_grenade_pocket_ecm_jammer = "The Application",
		bm_grenade_pocket_ecm_jammer_desc = "Full package may be required to qualify for benefits\n\nA small device for hacking and sending a hidden signal nearby. Pocket ECM has advanced algorithms for detecting and monitoring wireless data, which are useful for users when they are hiding in the shadows or in combat.",

		menu_st_spec_22 = "Ike",
		menu_st_spec_22_desc = "You are a selective fighting parasite and you hurt your enemies to strengthen yourself and your friends. More. It's not just a stone bag. You can relieve stress and use that anger to strengthen your team.",
		menu_deck22_1 = "Completion",
		menu_deck22_1_desc = "It opened, and there was a rush of cleaning.\n\nAfter changing the Old Buff, the ampoule of secretion will no longer appear. The Ample latch replaces the same shot that was fired. And you can express it as you wish.\n\nIn the game you can start cleaning the lamp with the $BTN_USE_ITEM;.\n\nIf you use an ampoule for leaching, turn on the ##40%## safe ampoule for leaching and switch off the device.\n\nThe level of energy increase increases your health by ##20%## and eliminates ##100%## of enemy losses. Killing both enemies temporarily restores life and prevents damage. If you lose weight, your peers will get 5% health.\n\nLeave the pressure on for ##30-6 seconds##.",
		menu_deck22_3 = "Can't Prove",
		menu_deck22_3_desc = "When the glass is hard, there is no blood flow, but if you feel pain, it is ##80%## slower.",
		menu_deck22_5 = "The Star",
		menu_deck22_5_desc = "The length of the hill plate has been increased by ##10## seconds.\n\nWhen the enemy dies, it goes off for ##1## second.\n\nIf they make a mistake, the health of the company will improve by ##10%##.",
		menu_deck22_7 = "A Couple of Houses",
		menu_deck22_7_desc = "Your overall health is improved by 20%.",
		menu_deck22_9 = "Gongsheng",
		menu_deck22_9_desc = "You can now temporarily activate the bottle and refill it until it is ready. If you successfully resurrect an ally or use a medical pouch before the bottle runs out, you can survive if your health is above ##0##.\n\nIn the ranking of a vial, the health status is divided into ##10%## segments.\n\nIncreases maximum health by 60%.\n\nPackage Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",
		bm_grenade_copr_ability = "Old Buff",
		bm_grenade_copr_ability_desc = "To wake up your lower extremities, break a small glass bladder under your nose and take a deep breath. You don't really know what's inside, but it hits the world and gives you adrenaline. One thing is for sure; Even if the salt doesn't come out.",

		menu_st_spec_23 = "What are you comparing?",
		menu_st_spec_23_desc = "Thanks to digital memory and photos, this model has become a phenomenon. Hope for an event that immediately awakens you so that you can protect and destroy it. You have researched other types of packing services and can copy their key skills to improve your skills. Combine techniques to create beautiful and unique styles. When others accuse you of stealing, remember that falling in love is actually a form of pride.",
		menu_deck23_1 = "Attack Again(choose to upgrade)",
		menu_deck23_1_desc = "The second car restarts ##10## times after the ##first## and ##last## collision. Increases engine conversion speed by up to ##320%##.",
		menu_deck23_3 = "Best Game(choose to upgrade)",
		menu_deck23_3_desc = "Each cop restores ##10## health.",
		menu_deck23_5 = "Is this your weapon?(choose to upgrade)",
		menu_deck23_5_desc = "The enemy shoot them a ##graduate##.",
		menu_deck23_7 = "It's A Good Time(choose to upgrade)",
		menu_deck23_7_desc = "When your health drops below ##50%##, you receive a powerful boost that drains your health over ##2## seconds. This happens every ##15## seconds.",
		menu_deck23_9_desc = "Package Performance Bonus - Increase your chances of getting a good product by ##10%## on payday.",

		menu_deck23_1_1 = "His suffering",
		menu_deck23_1_1_desc = "High health increased by 20%.",
		menu_deck23_3_1 = "His suffering",
		menu_deck23_3_1_desc = "High health increased by 20%.",
		menu_deck23_5_1 = "His suffering",
		menu_deck23_5_1_desc = "High health increased by 20%.",
		menu_deck23_7_1 = "His suffering",
		menu_deck23_7_1_desc = "High health increased by 20%.",

		menu_deck23_1_2 = "you work hard",
		menu_deck23_1_2_desc = "5% weapon chance.",
		menu_deck23_3_2 = "you work hard",
		menu_deck23_3_2_desc = "5% weapon chance.",
		menu_deck23_5_2 = "you work hard",
		menu_deck23_5_2_desc = "5% weapon chance.",
		menu_deck23_7_2 = "you work hard",
		menu_deck23_7_2_desc = "5% weapon chance.",

		menu_deck23_1_3 = "The mind of a cat",
		menu_deck23_1_3_desc = "Deposit capacity increased by 5%.",
		menu_deck23_3_3 = "The mind of a cat",
		menu_deck23_3_3_desc = "Deposit capacity increased by 5%.",
		menu_deck23_5_3 = "The mind of a cat",
		menu_deck23_5_3_desc = "Deposit capacity increased by 5%.",
		menu_deck23_7_3 = "The mind of a cat",
		menu_deck23_7_3_desc = "Deposit capacity increased by 5%.",

		menu_deck23_bonus_speed = "Permath Mosiarule",
		menu_deck23_1_4_desc = "Increases movement speed by 10% with the knee.",
		menu_deck23_3_4_desc = "Increases movement speed by 10% with the knee.",
		menu_deck23_5_4_desc = "Increases movement speed by 10% with the knee.",
		menu_deck23_7_4_desc = "Increases movement speed by 10% with the knee.",

		--New menu text
		
		--tabs
		menu_st_category_all = "Many",
		menu_st_category_offensive = "turn on",
		menu_st_category_defensive = "bali",
		menu_st_category_covert = "secret",
		menu_st_category_supportive = "support, support",
		menu_st_category_versatile = "It's a rare breed",
		menu_st_category_stealth = "Books.",
		menu_st_category_favorites = "state",

		--short card descriptions
		menu_specialization_tier1 = "Map 1",
		menu_specialization_tier3 = "three letters",
		menu_specialization_tier5 = "The fifth book",
		menu_specialization_tier7 = "from the seventh sheet",
		menu_specialization_tier9 = "Seven cards"

	})
end)