Hooks:Add("LocalizationManagerPostInit", "Payment_Date_2_Skills", function(loc)
	LocalizationManager:add_localized_strings({
		--Mastermind Tree
		menu_combat_medic_beta_desc = "Basic: ##1 point##\nDamage is reduced by ##30%## in ##5 seconds## while other players are healed.\n\nAce: 3 points\nRejuvenating the staff will increase your health by ##30%##.",	--Combat Medic
		menu_fast_learner_beta_desc = "Default: ##2 points##\nYour living members suffer ##30%## less than ##5 candle##.\n\nAcc: ##four points##\nIncreased damage limitation.\n##50%##.",	--Pain Killer
		menu_tea_time_beta_desc = "Getting started: ##2 points##\n##50%## discount on first aid kit and medical bag\n\nAce: ##4 points##\nTeam members using a first aid kit or medical bag receive a ##10%## discount. damage over ##120## seconds.",	--Quick Fix
		menu_medic_2x_beta_desc = "Default: ##3 points##\nYou can now use two bags instead of one.\n\nAce: ##6 points##\n##Two## more charges have been filed against this proceeding.",	--Combat Doctor
		menu_tea_cookies_beta_desc = "Topic: ##3 points##\nAdd the above ##seven## offers to your list of activities.\n\nS: ##6 prints##\nAdd the ##three volunteers## to your to -do list. First Aid Box Use it properly when the player lands within the first ##5 yards## of the fifth level. Financial aid. You cannot wake up more than once in ##20## seconds.",	--Uppers
		menu_inspire_beta_desc = "Source: ##Chapter 4##\nDevelop your employees ##100%## fast. to insult friends\nIncreases mobility by ##20%## in 10 seconds.\n\nAce: ##Chapter 8##\n##100%## chance to save your employees remotely They shouted at ##9## feet. This cannot be done ##once## every ##20 years.##\nThe second",	--Inspire

		menu_triathlete_beta_desc = "Source: ##1 point##\nIf you multiply the cable connection by ##four##, you can mortgage the cable at ##75%## Hurry up.\n\nAce: ##3 points##\nYou and your team hurt ##0.5## people every day. This effect overlaps with ##eight## side effects.\n\n\nNote: This ability does not negate the ability to force other players' friends.",	--Forced Friendship
		menu_joker_beta_desc = "Source: ##2 points##\nThe enemy cannot turn into a battle with you. You can't do it secretly and you can't surrender to the enemy You manage them.\nFor a while, you can only move one enemy.\n\nList: ##4th##\nThe stats deal an additional ##35%## damage to the enemy. lead time Defeated the enemy ##65%##.",	--Joker
		menu_cable_guy_beta_desc = "Introduction: ##2 points##\n\nIncrease your amazing power and limit it to 50.\n\nAlso known as: ##4 points##\nYou can have ##two## overwhelming enemies at once.",	--Confident
		menu_control_freak_beta_desc = "Start: ##3 points##\nEnemy variants increase your speed by ##10%##.\n\nConverted enemies lose ##45%## less.\n\nA: ##6 points##\nThis medicine increases your health by ##30%##.\n\nAdditional damage to modified enemies is reduced by ##54%##.",	--Partners in Crime
		menu_stockholm_syndrome_beta_desc = "Burns: ##3 points##\nUp to ##50%## of rum is a threat to people look:\n\nAcc: ##Sex Sex##\nIf you are saved from poverty, your kidnapper ##will not survive##. They give you prisoners as often as they take you. Return to good health. This can happen in an attack.\n##roof##",	--Stockholm Syndrome
		menu_black_marketeer_beta_desc = "Simple: ##Chapter 4##\nAt least for an event or a changed event Health increases by ##1.5%## every ##5## seconds.\n\nAs follows: ##Chapter 8##\nAt least for an event or a changed event Restore ##4.5%## of your health every ##5## seconds.",	--Hostage Taker

		menu_stable_shot_beta_desc = "Performance: Donkey: ##No.1##\nAchieve stability in ##8## weapons\n\nQ: ##No. 3##\nFind a total of ##16## magic weapons.",	--Stable Shot
		menu_sharpshooter_beta_desc = "Area: ##2 points##\nThe pistol, submachine gun and pistol are ##8## basic equipment. Continue the nature of the strokes.\n\nEast: ##4 miles away##\nIf you like all -round submachine guns, you get a ##20%## bonus. Cars and weapons with arrows.",	--Marksman
		menu_rifleman_beta_desc = "Condition: ##2##\nEscape uses all weapons ##100%## faster.\n\nThe use of artificial intelligence does not affect speed\n\nBeverage: ##n. Four##\nWeapons increased by ##25%## for all weapons. Your weapon This is clear from shotguns, grips and shotguns.\nMultiply by ##16##.",	--Rifleman
		menu_speedy_reload_beta_desc = "The reason is ##3 points##\nIncrease the speed of small SMGs, deceptive pistols, light pistols\n##fifteen%##\n\n##S6## numbers:\nShake your head to increase the loading speed by ##100%## in ##100## seconds.\nAll I had to do was shoot a gun, attack a Kalashnikov and die.\nThe query is simple.",	--Aggressive Reload
		menu_single_shot_ammo_return_beta_desc = "Date: ##3 points##\nIf you hit ##three shots## in ##6## seconds, you will be shot ##once## for each shot. SMG guns, guns, guns. It can work In shooting mode, press the instrument.\n\nThere are ##6 points##\nThe required number of steps is halved.",	--Ammo Effiency
		menu_sniper_graze_damage_desc = "Story: ##4 points##\nThe trunks that reach the pool lose about ##100## cm.\nDelay.\n\nExample: ##8 points##\nIf an arrow hits him in the head and kills him, the ##plant system## is released.\nWeapon ##20%##",		--Graze

		--Enforcer Tree
		menu_underdog_beta_desc = "Rule: ##1 point##\nIf you place three or more enemies within about ##10## meters, you will get it The bonus damage is ##15%## for ##7## seconds.\n\nRecommendation: ##3 points##\nIf you are attacked by three or more enemies within ##60## feet, the same goes for you. Use reduces damage by ##10%## for ##7## seconds.\n\nSymptoms: Wounded, smeared, or blown up in battle. Does not work Rocket.", --Underdog
		menu_shotgun_impact_beta_desc = "Base: ##2 points##\n##8x## increases the stability of the entire weapon. Damage caused to your weapon increases by ##5%##.\n\nSpeed: ##4 points##\nDamage caused to the weapon increases by ##10%##.", --Shotgun Impact
		menu_shotgun_cqb_beta_desc = "The standard is ##2 points##\nWeapon loading speed increased by 15%.\n\nMaster: ##4 points##\nWeapon loading speed increased by ##35%##. Steel size increased by ##125%##\nSpeed when using a weapon.", --Shotgun CQB
		menu_close_by_beta_desc = "Anchor point: ##3 points##\nYou can use your weapon to extinguish the fire while driving.\n\nAverage: ##6 points##\nIf you push the joint from below, the shooting speed will be ##35%##.\nExpand gun shops ##15## clips.", --Close By
		menu_far_away_beta_desc = "Arent Nog - ##points##\nSend it to Bhapara and add a nice gift ##40%:##\n\nSuch as: ##Name 6:##\nThe accuracy of the meter group has been increased by ##50%## Places to visit:", --Far Away
		menu_overkill_beta_desc = "Topic: ##4 points##\nKilling an enemy with an OVE9000 rifle or laptop will execute you. It can be said that tetidine increases by ##5## to ##20%## per second.\n\nControl: ##8 points##\nInjury bonuses now apply to all weapons. Must be active The OVE9000 provides a portable rifle or weapon. Up to ##0%##\n\n\nNote: personal injury, single use, grenade launcher or Rocket launchers.", --Overkill

		menu_oppressor_beta_desc = "Source: ##1 point##\n##15%## increase in income\n\nExample: ##3 points##\nThe limit of photo bag permanent recognition rate is ##75%.##", --
		menu_pack_mule_beta_desc = "Eggs: ##2 points##\nThis bag can be loaded with a ##50%## discount.\n\nArticle 20: ##4##\nPenalties for each weapon are reduced by ##1%##.", --
		menu_prison_wife_beta_desc = "Main: ##3 codes##\nUpgrade to ##5## shields for each successful title. Not really Every moment.\n\nEss: ##6 points##\n##20## more references have been successfully created and managed.", --
		menu_show_of_force_beta_desc = "Starting point: ##2 points##\nIf you save things, you will reduce your loss by ##50%##.\n\nLegs: ##4 points##\nAll coats have up to ##20## sleeves.", --
		menu_iron_man_beta_desc = "History: ##Part 3##\nA ##25%## improvement is good for you and your team.\n\nLot Chapter ##6##\nLet your weapon return to the enemy regularly Against them. Ways to increase the number of games increased Complete destruction of the weapon. give the fish ##100%.##", --
		menu_juggernaut_beta_desc = "General: ##None. 4##\nTotal price increased by ##30%##.\n\nAsia: ##8th##\nThis made the dress easier.", --

		menu_scavenging_beta_desc = "Basic terms: ##1 mark##\nThe ammunition table increased by ##50%##.\n\nDistance: ##3 points##\nEach of the six attacked enemies presents a special game with ammunition.", --
		menu_portable_saw_beta_desc = "Most important - ##2 points##\nA portable OE9000 is included that can be used as an auxiliary device.\n\nAsh - ##4 points##\nGet another trial version of OVE9000. tease Carbon monoxide increases cut resistance by ##40%##.", --
		menu_ammo_reservoir_beta_desc = "Default value: ##2 points##\nThe ammunition package thrown by the player allows the customer to shoot without the use of ammunition. Bullets can be used only ##5## seconds after the bullet is fired. Plus The higher the ammunition, the greater the effect.\n\nYes: ##4 points##\nIncrease the duration of the main result to ##15## seconds.", --
		menu_carbon_blade_beta_desc = "Basic rule: ##Type 3##\nIt can reduce hostile intolerance by as much as ##50%##.\n\nAnswer: ##6 notes##\nYou can now use the small OVE9000 Harvester to control enemy guards\nWhen you defeat an enemy with a puzzle, you have a ##50%## chance of defeating an enemy in your area.\nEnemies are scared ##10## meters away, fear pushes them a little\nIncredible horror outbreak", --
		menu_ammo_2x_beta_desc = "Maximum: ##3 points##\nNow you can put ##two## darts bags in one bag\n\nTroll: ##Session Session##\nCurrently there are ##50,000 bombs## in each bag", --
		menu_bandoliers_beta_desc = "Base: ##4 points##\nThe number of my electronic devices has increased by ##25%##.\n\nFood - ##8 points##\nIncrease weapons by up to ##75%##. You also have a ##5%## chance of being fired. Installation Each time you get a card, your chances increase by ##1%##. There are things to throw away. Look for options if a version is available This is very important.\n\nNote: Shipping Rewards do not apply for 'Closing'.", --

		--Technician Tree
		menu_defense_up_beta_desc = "Light cereals ##1##\nInstallation of security equipment decreased by ##5%##.\n\nBait: ##3 points##\nThere is a bullet in the back of the pistol.", --
		menu_eco_sentry_beta_desc = "Plans: ##Chapter 2##\nThe cost of providing security was reduced by ##5%##.\n\nSentence: ##Chapter 4##\nYour caregiver will improve your health by ##150%##.", --
		menu_sentry_targeting_package_beta_desc = "the first, ##No. 2##\nIncreases the accuracy of your weapon by ##100%##.\n\nBack: ##4##\nYour weapon rotation increases by ##150%##. Your weapon has ##50%## bombs.", --
		menu_jack_of_all_trades_beta_desc = "Leader: ##3 points##\nYou will soon lose ##100%## usage.\n\nAce: ##6 points##\nNow you can set the second level of portability. By setting the expandable object as the secondary speaker and setting it as the first expandable object, you can get half of what you need to learn.", --
		menu_engineering_beta_desc = "Fact: ##3 points##\nYou can now choose a defensive gun to reduce the chances of an enemy attack.\n\nX: ##6 points##\nIt now replaces the AP Centri missile, which reduces fire by ##75## and damages enemies and shields by ##250## by.", --
		menu_tower_defense_beta_desc = "Average: ##4 points##\nIt comes in ##orange##.\n\nIn ##eight##\n##Two## orange weapons were added.", --

		menu_hardware_expert_beta_desc = "Formula ##1 content##\nAdjust the experience and increase the speed by ##25%##. Drilling and cutting is smooth. Residents and security personnel must be trained without weapons to receive warnings.\n\nScore: ##3 points##\nThis gives you ##10## chances to start again after entering and leaving the scene.\n\nNote: Performance does not affect the OVE9000 puzzle.", --
		menu_drill_expert_beta_desc = "Channel: ##2 characters##\nDredging time is less than ##15%##.\n\nAce: ##4 points##\nDrilling time is further reduced by ##15%##.\n\nNote: This feature does not affect the ability to view OVE9000.", --
		menu_combat_engineering_desc = "Basic ##2##\nIncrease my goal by ##30%##.\n\nTags: ##a 4##\n##50%## increase in risk", --
		menu_kick_starter_beta_desc = "Serve: ##3 points##\nAfter a break, start ##20## exercises automatically with extra powder.\n\nAce: ##6 points##\nThis allows you to repair drill bits and dust in combat attacks. This feature has a ##50%## chance of drying and repairing. This function can only be used once for drilling and sawing.\n\nNote: Volume does not affect OVE9000 components.", --
		menu_more_fire_power_desc = "##3 points## added\nYou get a ##fee## and ##four## surveyors.\n\nEss: ##6 points##\nIn addition, you receive ##two## coin tosses and ##seven## employees.", --
		menu_fire_trap_beta_desc = "Bottom: ##4 points##\nYour turbine ignites a ##4m## explosion in ##10## seconds.\n\nExample: ##8 characters##\nIncreases the length of the fire power by ##10## seconds and the range of fire power by ##50%##.", --

		menu_steady_grip_beta_desc = "Edit: ##1 point##\nLearn the truth about the ##eight## tools.\n\nBait-##3 points##\nStrengthen your weapons when you are ##16## years old.", --
		menu_fire_control_beta_desc = "Serve: ##2 points##\nTake the subtlety of the ##12## arms of the hips.\n\nAss: ##4 points##\nShoot accurately while running and decrease the penalty by ##20%##.", --
		menu_heavy_impact_beta_desc = "Note: ##Number 2##\nAll enemies except Bulldogs and Captain Winter have a ##5%## chance of being shot.\n\n1: ##4##\nThis will increase treatment by up to ##20%##.", --
		menu_shock_and_awe_beta_desc = "Base: ##3 points##\nYou can shoot from behind with a pistol while running.\n\nLiquidity: ##6 degrees##\nAutomatically defeat two enemies with a submachine gun, light machine gun, assault rifle, or special weapon to improve recovery speed after 100. This reward reduces the size of the bullet by ##1%## to over ##20## records and increases the restart rate up to ##40##. %.", --
		menu_fast_fire_beta_desc = "Base: ##3 points##\nPistols: Firearms, machine guns, and rifles require an additional ##15## copies. This does not affect the strength of the masonry and the road axis.\n\nAce: ##6 points##\nWeapons can be similar to enemy weapons.\n\nNote: Do not use firearms.", --
		menu_body_expertise_beta_desc = "Preparation. ##Chapter 4:##\n##30%## of the damage is done to the enemy. In the event of a fire, you can use firearms, machine guns or special weapons.\n\nAuthor: ##Chapter 8:##\n##90%## of the damage when playing with opponents fell on my head. In the event of a fire, you can use firearms, machine guns or special weapons.", --

		--Ghost Tree
		menu_jail_workout_beta_desc = "Base: ##1 lb.##\nThe detection time is increased by ##25%## during pregnancy. You can also find enemies in external level mode.\n\nExperience: ##3 points##\nYou can write anything you want at home. You can get ##30%## more value for your savings and money.", --
		menu_chameleon_beta_desc = "Source: ##paragraph 2##\nWith a pressure of ##3.5## seconds, you can instantly detect enemies at a distance of ##10## meters around you\n\nKnowledge: ##point 4##\nYou can access all interior items. With the deaths of civilians, health care costs have fallen by ##75%##.", --
		menu_cleaner_beta_desc = "Base: ##2 points##\nGet ##more## body bags on your list. The storage capacity for the package has also increased by ##three##.\n\nTrumpet:## # 4##\nYou can put ##two## boxes in the bag.", --
		menu_ecm_booster_beta_desc = "Removal: ##3 points##\nYour ##pain## and ECM time increased by ##25%##.\n\nVOC: ##6 steps##\n##Unfortunately##, you can only use ECM to open ports.", --
		menu_second_chances_beta_desc = "Technical features: ##3 points##\nYou can identify yourself and your staff by shooting ##one## camera. Results will arrive within ##25## seconds.\n\nNCEES: ##6 points##\nYou can read ##100% faster##. You can turn it off.", --
		menu_ecm_2x_beta_desc = "Main: ##4 points##\n##Two## ECM switches can be installed in one place.\n\nRating: ##8 points##\nECM response time increased by ##25%##, ECM response time increased by ##25%##. ECM alerts will slow down the attack mechanism.", --

		menu_sprinter_beta_desc = "Key points: ##article 1##\nStamina starts at ##25%## faster and speed increases by ##25%##. The speed rate also increased by ##25%##.\n\nWriting: ##3 points##\nThe storage capacity of the spline increased by ##10%##, but the storage capacity of the spline increased by ##15%##.", --
		menu_thick_skin_beta_desc = "Base - ##2 marks##\nHide Spider ##2##\n\nNet - ##4 points##\nHide all ball jackets ##4##", --
		menu_awareness_beta_desc = "Chapter: ##2 points##\nClimbing stairs offers ##10%## more speed and ##20%## more speed\n\nAce: ##4 points##\nYou can run in any direction\n\n\nStart and restart: You can restart the weapon using Sprint.", --
		menu_insulation_beta_desc = "Original: ##3 characters##\nBy affecting the sweetening process, up to ##30%## of the ##flavor## and effect will be lost.\n\nBack: ##6 points##\nAfter completing the ##test##, you can switch from one ##flavor## to another in a few seconds.", --
		menu_dire_need_beta_desc = "Give - ##3 points##\nWhen your weapon is damaged, the ##first## blow will help all the enemies. These benefits are lost when the device is replaced.\n\nYeah. ##6 points##\nFor ##six## years, European arms were traded.", --
		menu_jail_diet_beta_desc = "Getting Started ##Chapter 4:##\nWith a probability of ##1%##, one in three is less than ##35-10%##.\n\nHow: ##8:##\nWith a probability of ##1%##, the sample falls below ##35-10%##.", --

		menu_scavenger_beta_desc = "Basic - ##1 point##\nIf your defense collides with your strength, your speed will increase by ##30%## in ##5## seconds.\n\nTSO: ##3 points##\nThese benefits also apply when your team starts.", --
		menu_silence_expert_beta_desc = "Standard: ##2 points##\nSilent Weapon provides stability for ##eight## weapons and ##100%## zoom speed.\n\nAce: ##4 points##\nSilent Weapons focuses on ##12## weapons.", --
		menu_optic_illusions_desc = "Title: ##A2##\nYou have ##35%## no enemy plan.\n\nACE: ##Name 4##\nYou will wear a helmet for ##each## weapon. Cover expenses. Reduce the fine", --
		menu_spotter_teamwork_beta_desc = "The basis is ##3 points##\nEnemies are ##15%## more likely to be defeated.\n\nA: ##6 points##\nEnemies inflict ##50%## more damage when they are more than ##10## meters away. You can attack them with any weapon, increasing the enemy's capacity by ##100%##.", --
		menu_backstab_beta_desc = "Basic Principles-##3 Signs##\n##Three## of them are important: the diagnosis is less than ##35##-##30##.\n\nAce: ##6 points##\nFor information, there is a ##3## to ##35## to ##30## percent chance.\n\n\nNote: Do not use the grenade launcher.", --
		menu_unseen_strike_beta_desc = "Base: ##4 points##\nIf the device expires in ##4## seconds, the critical time is ##35%## in ##6## seconds.\n\nYes: ##8 points##\nIncreases beating time to ##18## seconds.\n\n\nIf you make a mistake, the benefits will be lost.", --

		--Fugitive Tree
		menu_equilibrium_beta_desc = "Background: ##Level 1##\nThe pockets are low and the front of the hand is ##33%##.\n\nYes: ##3 points##\nReach ##8## Pistol Accuracy with all pistols.", --
		menu_akimbo_skill_beta_desc = "Above: ##2 points##\nAkimba's excellent performance has also been reduced to ##eight## nights.\n\nYes: ##4 points##\nThe company also reduced interest rates to ##8## and delivered up to ##50%## of missiles.", --
		menu_dance_instructor_desc = "Simple: ##2 points##\nThe size of the machine gun is divided into ##five##.\n\nNu: ##4 points.##\nWeapon prices are rising by ##50%##.", --
		menu_expert_handling_desc = "Basic: ##3 points##\nEveryone will get a ##10%## reward and ##4## penalties for every successful attack, lasting ##10## seconds.\n\nAce: ##6 points##\n##50%## of all weapons will be loaded immediately.", --
		menu_gun_fighter_beta_desc = "Medal - ##3 points##\nEach area injury increased by ##5## points.\n\n##6 points##\nDamage to the lower part of the barbell ##10## additional injuries.", --
		menu_trigger_happy_beta_desc = "Size: ##4 points##\nThe wound heals ##120%## and lasts for ##two## seconds.\nIt happens right away.\n\nAverage: ##eight##\nIncreases emergency time by ##4## seconds.", --

		menu_nine_lives_beta_desc = "Basic information: ##1 point##\nBlood flow increased by ##50%##.\n\nLunch: ##3 points##\nIt can be built before it is ##closed##.", --
		menu_up_you_go_beta_desc = "TOTAL: ##2 points##\nRepeat every ##10## seconds. Damage is reduced multiple times every ##10## seconds.\n\nYes ##4 points##\n##40%## catering wishes", --
		menu_running_from_death_beta_desc = "Easy: ##2 points##\n##10## seconds after activating and switching weapons, the loading speed increases by ##100%##.\n\nAce: ##4 points##\nThe speed increases by ##30%## within ##10## seconds after use.", --
		menu_feign_death_desc = "Significance: ##Chapter three.##\nOtherwise, the ##15## chances increase immediately.\n\nInstrument: ##Chapter Six.##\nThen the chance of a cure increases to ##30##.", --
		menu_perseverance_beta_desc = "From: ##3 points##\nInstead of falling, walking before a ##60%## drop is good and allows you to keep fighting for ##three## seconds.\n\nInvestigate: Don't work if you're sick of it.\n\nMouse: ##no. 6##\nThe duration of the 'POONCH' music is increased by ##three## seconds. Hm, sure, yes, I know because it was known in advance.", --
		menu_pistol_beta_messiah_desc = "Activities; ##part 4##\nWhen you defeat the enemy, it will ##bleed##. When he was attacked.\n\nSize: ##8 items##\nYou will pay Christ's ##debt## when you use your doctor's account.", --

		menu_martial_arts_beta_desc = "Research - ##section.##\n##50%## damaged all attack attacks. During training.\n\nEssay - ##chapter 3##\nThe chance of killing enemies is almost ##50%## higher.", --
		menu_steroids_beta_desc = "Rating: ##2 points##\nAttacks enemies with ##100%## more damage.\n\nCommunication: ##Chapter 4:##\nAttack aggressive battles and destroy ##100%## more against special enemies.", --
		menu_bloodthirst_desc = "Base: ##2 points##\nEach murder increases the risk of further accumulation from ##100%## to ##1600%##. This effect is restored when you defeat the enemy in a sudden attack.\n\nASO: ##4 points##\nEach time you win an enemy battle, the speed increases from ##50## to ##10## seconds.", --
		menu_wolverine_beta_desc = "The basis is ##3 points##\nThe lower your health, the greater the risk. If your health is below ##50%##, you will deal ##250%## more damage.\n\nEssay - ##6 points##\nThe lower your health, the greater the risk. If you have less than ##50%## health, you will take ##100%## more damage from the weapon in several areas.\n\nNote: Not suitable for use with food. Grenade launchers or rocket launchers\n\nThird party updates will be removed when Sea Bear's status changes.", --
		menu_drop_soap_beta_desc = "Original: ##3 points##\nIntroducing an armed struggle prevents the enemy from attacking you and running. The result is not harmful.\n\nNext step: ##6 points##\nHe attacks the organization by force and returns it.", --
		menu_frenzy_desc = "Main source - ##4 points##\nYou can only restore ##30%## of your health, it cannot be restored, but this reduces your losses by ##10-75%##.\n\nEsny -##8 points##\nDamage reduced by ##25%## and bumpers by ##0%##." --
	})
end)