local text_original = LocalizationManager.text
local testAllStrings = false  --Set to true to show all string ID's, false to return to normal.
function LocalizationManager:text(string_id, ...)

return string_id == "bm_w_aa12"    and "a cow"
or string_id == "bm_w_ak12"    and "king's son"
or string_id == "bm_w_ak5"    and "its okay"
or string_id == "bm_w_ak74"    and " Madagascar"
or string_id == "bm_w_akm"     and "a paper box"
or string_id == "bm_w_akm_gold"     and "in the workplace"
or string_id == "bm_w_akmsu"     and "finish it"
or string_id == "bm_w_amcar"     and "Please, do not do that"
or string_id == "bm_w_arbiter"     and "milk"
or string_id == "bm_w_asval"     and "Under the car"
or string_id == "bm_w_aug"     and "This is country"
or string_id == "bm_w_b682"     and "eat"
or string_id == "bm_w_b92fs"     and "El clima es caliente"
or string_id == "bm_w_baka"     and "microorganisms."
or string_id == "bm_w_basset"     and "Cigarette machine"
or string_id == "bm_w_beer"     and "Issue"
or string_id == "bm_w_benelli"     and "Ben Lee"
or string_id == "bm_w_boot"     and "death force"
or string_id == "bm_w_breech"     and "From the great nation of the gun itself"
or string_id == "bm_w_c96"     and "to swim"
or string_id == "bm_w_china"     and "on Thursday"
or string_id == "bm_w_chinchilla"     and "or"
or string_id == "bm_w_ching"     and "in the future"
or string_id == "bm_w_coach"     and "how to pronounce it"
or string_id == "bm_w_coal"     and "stay away"
or string_id == "bm_w_cobray"     and "a piece of clothing"
or string_id == "bm_w_colt_1911"     and "management concept"
or string_id == "bm_w_contraband"     and "FRIEND"
or string_id == "bm_w_corgi"     and "Президент"
or string_id == "bm_w_czech"     and "Look at the car"
or string_id == "bm_w_deagle"     and "to imitate"
or string_id == "bm_w_desertfox"     and "So here it is."
or string_id == "bm_w_erma"     and "uterus in his mouth"
or string_id == "bm_w_fal"     and "soup"
or string_id == "bm_w_famas"     and "grandfather"
or string_id == "bm_w_flamethrower_mk2"     and "lamps"
or string_id == "bm_w_g22c"     and "and people"
or string_id == "bm_w_g3"     and "fill out"
or string_id == "bm_w_g36"     and "money"
or string_id == "bm_w_galil"     and "Report"
or string_id == "bm_w_glock_17"     and "black shirt"
or string_id == "bm_w_glock_18c"     and "Simon's car"
or string_id == "bm_w_gre_m79"     and "come back"
or string_id == "bm_w_hajk"     and "he is not here"
or string_id == "bm_w_hk21"     and "Done"
or string_id == "bm_w_holt"     and "Wood"
or string_id == "bm_w_hs2000"     and "Aslan"
or string_id == "bm_w_hunter"     and "A gun is a gun"
or string_id == "bm_w_huntsman"     and "Moscow"
or string_id == "bm_wp_pis_g26"     and "Our group"
or string_id == "bm_w_judge"     and "Control"
or string_id == "bm_w_komodo"     and "cook in oil"
or string_id == "bm_w_ksg"     and "Entertainment center"
or string_id == "bm_w_l85a2"     and "The evil queen"
or string_id == "bm_w_legacy"     and "Do it yourself"
or string_id == "bm_w_lemming"     and "Headphones"
or string_id == "bm_w_long"     and "in the long summer"
or string_id == "bm_w_m134"     and "It's useless."
or string_id == "bm_w_m14"     and "to know"
or string_id == "bm_w_m16"     and "Court:"
or string_id == "bm_w_m1897"     and "interval"
or string_id == "bm_w_m1928"     and "summer in chicago"
or string_id == "bm_w_m249"     and "My Love"
or string_id == "bm_w_m32"     and "little bacon"
or string_id == "bm_w_m37"     and "blanco"
or string_id == "bm_w_m4"     and "carbohidratos"
or string_id == "bm_w_m45"     and "in january"
or string_id == "bm_w_m60"     and "The first drop of blood"
or string_id == "bm_w_m95"     and "He died"
or string_id == "bm_w_mac10"     and "the market"
or string_id == "bm_w_mateba"     and "The text"
or string_id == "bm_w_mg42"     and "Wonderful"
or string_id == "bm_w_model3"     and "He lives in France"
or string_id == "bm_w_model70"     and "send"
or string_id == "bm_w_mosin"     and "don't forget"
or string_id == "bm_w_mp5"     and "big feet"
or string_id == "bm_w_mp7"     and "personal service"
or string_id == "bm_w_mp9"     and "It is very difficult."
or string_id == "bm_w_msr"     and "blind snake"
or string_id == "bm_w_olympic"     and "between the brackets"
or string_id == "bm_w_p226"     and "above all"
or string_id == "bm_w_p90"     and "That's good"
or string_id == "bm_w_packrat"     and "Traders"
or string_id == "bm_w_par"     and "Free delivery"
or string_id == "bm_w_peacemaker"     and "merry christmas!"
or string_id == "bm_w_pl14"     and "This is not true."
or string_id == "bm_w_polymer"     and "start"
or string_id == "bm_w_ppk"     and "Glover closed his eyes."
or string_id == "bm_w_r700"     and "increase" 
or string_id == "bm_w_r870"     and "I heard it again"
or string_id == "bm_w_r93"     and "A new jacket"
or string_id == "bm_w_raging_bull"     and "dumb"
or string_id == "bm_w_ray"     and "good friend" 
or string_id == "bm_w_winchester1874"     and "what do you say"
or string_id == "bm_w_rota"     and "elsewhere"
or string_id == "bm_w_rpg7"     and "You can pass"
or string_id == "bm_w_rpk"     and "of course"
or string_id == "bm_w_s552"     and "turkey"
or string_id == "bm_w_saiga"     and "Будь обережний"
or string_id == "bm_w_saw"     and "_____ Date"
or string_id == "bm_w_sbl"     and "butter"
or string_id == "bm_w_scar"     and "doing"
or string_id == "bm_w_schakal"     and "in love"
or string_id == "bm_w_scorpion"     and "nine"
or string_id == "bm_w_serbu"     and "my God"
or string_id == "bm_w_shepheard"     and "Yes"
or string_id == "bm_w_shrew"     and "the police"
or string_id == "bm_w_shuno"     and "A little silly"
or string_id == "bm_w_siltstone"     and "phone"
or string_id == "bm_w_slap"     and "the face"
or string_id == "bm_w_sparrow"     and "pot"
or string_id == "bm_w_spas12"     and "go hunting"
or string_id == "bm_w_sr2"     and "demonstrate"
or string_id == "bm_w_stech"     and "Dr. Bartek."
or string_id == "bm_w_sterling"     and "I am ballast"
or string_id == "bm_w_striker"     and "his head"
or string_id == "bm_w_sub2000"     and "the room"
or string_id == "bm_w_system"     and "Please help me"
or string_id == "bm_w_tec9"     and "This is a very important question"
or string_id == "bm_w_tecci"     and "Friends!"
or string_id == "bm_w_tti"     and "Falling in love"
or string_id == "bm_w_usp"     and "on the floor"
or string_id == "bm_w_uzi"     and "you know"
or string_id == "bm_w_vhs"     and "said the lion."
or string_id == "bm_w_wa2000"     and "He was joking."
or string_id == "bm_w_plainsrider"     and "a big circle"
or string_id == "bm_w_elastic"     and "part of the rainbow"
or string_id == "bm_w_vityaz"     and "good company"
or string_id == "bm_w_m590"     and "Oprah"
or string_id == "bm_w_m1911"     and "Dizziness"
or string_id == "bm_w_qbu88"     and "You are still there"
or string_id == "bm_w_pm9"     and "indeed"
or string_id == "bm_w_groza"     and "from the kitchen"
or string_id == "bm_w_shak12"     and "good rain"
or string_id == "bm_w_type54"     and "I don't like chicken."
or string_id == "bm_w_rsh12"     and "urine"

or string_id == "bm_w_jowi"     and "Pequeña estructura"
or string_id == "bm_w_x_1911"     and "De pie en la cruz"
or string_id == "bm_w_x_2006m"     and "believe your boss"
or string_id == "bm_w_x_akmsu"     and "delete reference"
or string_id == "bm_w_x_b92fs"     and "Then Brent."
or string_id == "bm_w_x_baka"    and "Also micro USB"
or string_id == "bm_w_x_basset"     and "evil man"
or string_id == "bm_w_x_beer"     and "The city itself"
or string_id == "bm_w_x_breech"     and "A case of discrimination"
or string_id == "bm_w_x_c96"     and "Yellow"
or string_id == "bm_w_x_chinchilla"     and "other products"
or string_id == "bm_w_x_coal"     and "big factory"
or string_id == "bm_w_x_cobray"     and "A big shirt"
or string_id == "bm_w_x_czech"     and "Keep running Ambo."
or string_id == "bm_w_x_deagle"     and "Here"
or string_id == "bm_w_x_erma"     and "arms and legs"
or string_id == "bm_w_x_g17"     and "black magic"
or string_id == "bm_w_x_g18c"     and "over there"
or string_id == "bm_w_x_g22c"     and "We have positive feedback about our company."
or string_id == "bm_w_x_hajk"     and "oil"
or string_id == "bm_w_x_holt"     and "world"
or string_id == "bm_w_x_hs2000"     and "What a fool!"
or string_id == "bm_w_x_judge"     and "good judge"
or string_id == "bm_w_x_legacy"     and "What is the weight of the bottle?"
or string_id == "bm_w_x_m1928"     and "What is Akiba Chicago like?"
or string_id == "bm_w_x_m45"     and "Sweden"
or string_id == "bm_w_x_mac10"     and "Sign the bottle"
or string_id == "bm_w_x_model3"     and "penis"
or string_id == "bm_w_x_mp5"     and "Playing with religion"
or string_id == "bm_w_x_mp7"     and "especially in the mountains"
or string_id == "bm_w_x_mp9"     and "Hard"
or string_id == "bm_w_x_olympic"     and "The same."
or string_id == "bm_w_x_p226"     and "Photo of Jumbo"
or string_id == "bm_w_x_p90"     and "Rice is distributed under the feet."
or string_id == "bm_w_x_packrat"     and "Akemba merchants"
or string_id == "bm_w_x_pl14"     and "White dunes"
or string_id == "bm_w_x_polymer"     and "a long way"
or string_id == "bm_w_x_ppk"     and "The men are down."
or string_id == "bm_w_x_rage"     and "This is a bronchus."
or string_id == "bm_w_x_rota"     and "He tapped her on the shoulder."
or string_id == "bm_w_x_schakal"     and "News about the wolf."
or string_id == "bm_w_x_scorpion"     and "A snake's life"
or string_id == "bm_w_x_shepheard"    and "to run"
or string_id == "bm_w_x_shrew"     and "results in 1 minute"
or string_id == "bm_w_x_sparrow"     and "gothic girl"
or string_id == "bm_w_x_sr2"     and "Hi Heather,"
or string_id == "bm_w_x_stech"     and "Akimbo Igor Otto: Do ​​you need more customers?"
or string_id == "bm_w_x_sterling"     and "right here"
or string_id == "bm_w_x_tec9"     and "Sting detonation"
or string_id == "bm_w_x_usp"     and "a knife"
or string_id == "bm_w_x_uzi"     and "you go to university"
or string_id == "bm_w_x_vityaz"     and "success"
or string_id == "bm_w_x_m1911"     and "and Ocampo"
or string_id == "bm_w_x_pm9"     and "Gongshan put his hands on his knees."
or string_id == "bm_w_x_type54"     and "Akibglud"
or string_id == "bm_w_x_lemming"     and "Let's go together"
or string_id == "bm_w_x_rsh12"     and "The tiger is alive"

or string_id == "bm_w_ultima"     and "I'm afraid."
or string_id == "bm_w_maxim9"     and "Clear instructions"
or string_id == "bm_w_x_maxim9"     and "This is very annoying."
or string_id == "bm_w_fmg9"     and "food"
or string_id == "bm_w_x_fmg9"     and "The road is closed"

or string_id == "bm_w_hk51b"     and "it is hidden"
or string_id == "bm_w_scout"     and "and teeth"
or string_id == "bm_w_ms3gl"     and "what"

or string_id == "bm_grenade_dada_com"     and "you think baby"
or string_id == "bm_concussion"     and "Motorcycle helmet"
or string_id == "bm_grenade_tag_team"     and "nectar"
or string_id == "bm_grenade_electric"     and "He promised you"
or string_id == "bm_grenade_damage_control"     and "a book"
or string_id == "bm_grenade_pocket_ecm_jammer"     and "the onset of near-death experiences"

or string_id == "bm_w_hailstorm"     and "Welcome"
or string_id == "bm_w_sko12"     and "has"
or string_id == "bm_w_x_sko12"     and "Akimbo story."
or string_id == "bm_w_korth"     and "crazy"
or string_id == "bm_w_x_korth"     and "a clay monk"

or string_id == "bm_w_victor"     and "In brief"


or testAllStrings == true and string_id
or text_original(self, string_id, ...)
end

